In [9]:
import pandas as pd
import numpy as np
import re
import unicodedata
from underthesea import text_normalize, word_tokenize

In [26]:
# Đọc dữ liệu
df = pd.read_csv('data/data.csv')
df

,title,url,texts,author,category,published_at,source,content_block
0,Lao động trung niên tìm việc nhiều nhưng thị t...,https://vnexpress.net/lao-dong-trung-nien-tim-...,Gần 40% số người tìm việc thuộc nhóm trung niê...,Lê Tuyết,Thời sự,"Thứ tư, 8/4/2026, 00:00 (GMT+7)",VnExpress,"[{'type': 'text', 'content': 'Gần 40% số người..."
1,Tổng Bí thư Tô Lâm gặp mặt cán bộ Văn phòng Ch...,https://vnexpress.net/tong-bi-thu-to-lam-gap-m...,Sau khi được Quốc hội bầu giữ chức Chủ tịch nư...,Vũ Tuân,Thời sự,"Thứ ba, 7/4/2026, 22:40 (GMT+7)",VnExpress,"[{'type': 'text', 'content': 'Sau khi được Quố..."
2,Nhiệt độ nhiều nơi vượt 40 độ C,https://vnexpress.net/nhiet-do-nhieu-noi-vuot-...,Cả nước bước vào ngày thứ hai của đợt nắng nón...,Gia Chính,Thời sự,"Thứ ba, 7/4/2026, 20:49 (GMT+7)",VnExpress,"[{'type': 'text', 'content': 'Cả nước bước vào..."
3,Các ủy ban của Quốc hội kiện toàn nhân sự,https://vnexpress.net/cac-uy-ban-cua-quoc-hoi-...,"Ngày 7/4, Hội đồng Dân tộc và một số Ủy ban củ...",Sơn Hà,Thời sự,"Thứ ba, 7/4/2026, 20:30 (GMT+7)",VnExpress,"[{'type': 'text', 'content': 'Ngày 7/4, Hội đồ..."
4,Cháy nhà 4 tầng ở trung tâm TP HCM,https://vnexpress.net/chay-nha-4-tang-o-trung-...,Khói lửa bùng lên từ lầu một ngôi nhà gần ngã ...,Đình Văn,Thời sự,"Thứ ba, 7/4/2026, 17:45 (GMT+7)",VnExpress,"[{'type': 'text', 'content': 'Khói lửa bùng lê..."
...,...,...,...,...,...,...,...,...
2295,"Cận Vía Thần Tài, một Tiệm vàng lớn tuyên bố c...",https://cafebiz.vn/can-ngay-via-than-tai-mot-t...,Tiệm vàng với 34 cơ sở trên toàn quốc khẳng đị...,Phan Trang,BizMoney,24/02/2026 10:59 AM,CafeBiz,"[{'type': 'text', 'content': 'Tiệm vàng với 34..."
2296,Giá vàng sáng 24/2 vượt 5.200 USD/ounce,https://cafebiz.vn/gia-vang-sang-24-2-vuot-520...,"Chỉ trong một ngày, giá vàng đã có mức tăng mạ...",Huyền Băng,BizMoney,24/02/2026 07:10 AM,CafeBiz,"[{'type': 'text', 'content': 'Chỉ trong một ng..."
2297,Giá vàng thế giới chạm mốc 5.200 USD/ounce,https://cafebiz.vn/gia-vang-the-gioi-cham-moc-...,Thị trường vàng ngày càng nóng lên.. Trong 24 ...,Băng Băng,BizMoney,23/02/2026 22:25 PM,CafeBiz,"[{'type': 'text', 'content': 'Thị trường vàng ..."
2298,"Trước ngày vía Thần Tài: Không chỉ vàng, giá b...",https://cafebiz.vn/truoc-ngay-via-than-tai-kho...,"Tại thị trường trong nước, giá bạc cũng đã tăn...",Ngọc Tú,BizMoney,23/02/2026 10:20 AM,CafeBiz,"[{'type': 'text', 'content': 'Tại thị trường t..."
2299,Giá vàng thế giới lội ngược dòng trong Tết Ngu...,https://cafebiz.vn/gia-vang-the-gioi-loi-nguoc...,Thị trường vàng đã có cú lội ngược dòng trong ...,Huyền Băng,BizMoney,23/02/2026 08:57 AM,CafeBiz,"[{'type': 'text', 'content': 'Thị trường vàng ..."

In [21]:
# Xoá html code trong dữ liệu
def remove_html(text):
    return re.sub(r'<[^>]*>', '', text)

In [ ]:
# Chuẩn hoá về bảng mã Unicode, kiểu gõ dấu tiếng việt và chữ viết thường
def normalize(text):
    text = unicodedata.normalize('NFC', text)
    text = text_normalize(text)
    text = text.lower()
    return text

In [ ]:
# Xoá các ký tự đặc biệt và các khoảng cách thừa
def remove_special_characters(text):
    text = re.sub(r'[^\w\sàáảãạăắằẳẵặâấầẩẫậđèéẻẽẹêếềểễệìíỉĩịòóỏõọôốồổỗộơớờởỡợùúủũụưứừửữựỳýỷỹỵ]', ' ', text)
    text = re.sub(r'\s+', ' ', text)
    return text.strip()

In [17]:
# Loại bỏ stopword
with open('data/vietnamese-stopwords.txt', encoding='utf-8') as f:
    stopwords = set(f.read().splitlines())
    
def remove_stopwords(text):
    tokens = word_tokenize(text)
    text_filterd = [word for word in tokens if word not in stopwords]
    return ' '.join(text_filterd)

In [19]:
def preprocessing(texts):
    result = []
    for text in texts:
        text = remove_html(text)
        text = normalize(text)
        text = remove_special_characters(text)
        text = remove_stopwords(text)
        result.append(text)
    return result

In [ ]:
result = preprocessing(df['texts'])
result

['40 trung niên 36 49 song doanh nghiệp nhu cầu thay ưu tiên trẻ 18 35 thông tin ghi nhận báo cáo thị trường lao động quý 1 trung tâm dịch vụ việc làm tp hcm sở nội vụ nhu cầu tuyển dụng khả năng cung ứng thị trường song doanh nghiệp hướng lao động trẻ dữ liệu trụ sở tiếp nhận trung tâm ghi nhận 52 600 nhu cầu doanh nghiệp tuyển 82 700 thị trường trạng thái cầu vượt cung phân bổ đồng đều trình độ ngành nghề 36 49 dẫn đầu cung 21 000 tương đương 40 25 35 38 tuyển dụng độ nhu cầu tuyển dụng 36 49 0 32 doanh nghiệp ưu tiên lao động trẻ 18 35 41 phân tích nguyên nhân nguyễn văn hạnh thục giám đốc trung tâm dịch vụ việc làm tp hcm lao động trung niên chiếm tỷ lệ chủ yếu tích lũy kinh nghiệm xu hướng cải thiện thu nhập môi trường làm việc phân khúc thị trường nhân lực lao động phổ thông chiếm 33 tương đương 27 600 doanh nghiệp trình độ 82 nhu cầu tuyển dụng bằng cấp trung học phổ thông trở nhu cầu chủ yếu khu công nghiệp khu chế xuất ưu tiên lao động trẻ thích nghi sản xuất lệch pha cung cầu lao động trung niên kinh nghiệm nhu cầu ngành sản xuất kỹ thuật đòi hỏi kỹ năng thực hành khả năng tiếp cận công nghệ thục hẳn tín hiệu lo lao động kinh nghiệm trình độ việc làm quan hệ kênh tuyển dụng trung tâm dịch vụ việc làm tp hcm ghi nhận 58 tương đương 48 000 việc làm giới hạn độ lao động trung niên ngành sản xuất cơ khí bảo trì vận hành máy nhân lực tay nghề lao động giàu kinh nghiệm lĩnh vực hàng dịch vụ khả năng tiếp nhận lao động phổ thông thông qua khóa đào tạo ngắn hạn dự báo quý 2 nhu cầu tuyển dụng dao động 60 000 75 000 doanh nghiệp đẩy mạnh sản xuất cung nhẹ lao động xu hướng ưu tiên ổn định giai đoạn biến động đầu',
 'quốc hội bầu chức chủ tịch nhiệm kỳ 2026 2031 tổng bí thư tô lâm gặp mặt cán bộ văn phòng chủ tịch tinh gọn tinh nhuệ kín đáo sâu sát dự nguyên chủ tịch lương cường chánh văn phòng trung ương đảng phạm gia túc phó chủ tịch võ thị ánh xuân chủ nhiệm văn phòng chủ tịch lê khánh hải phát biểu gặp mặt tổng bí thư chủ tịch tô lâm ghi nhận tinh thần làm việc nghiêm túc nếp hiệu quả cán bộ công chức viên chức lao động văn phòng chủ tịch nhiệm vụ tiến độ chất lượng bảo mật nghi lễ hoàn thành trách nhiệm nhấn mạnh đất nước giai đoạn phát triển đòi hỏi tốc độ chất lượng hiệu quả bền vững văn phòng chủ tịch vai trò cơ quan tham mưu phục vụ toàn diện chính xác tin cậy tổng bí thư chủ tịch văn phòng tập thể tinh gọn tinh nhuệ chuẩn mực năng động kín đáo sâu sát bản lĩnh chuyên nghiệp hiện đại cán bộ nâng chất lượng tham mưu làm việc trách nhiệm trình độ chuyên môn nêu văn phòng chủ tịch chấp nhận qua loa tùy tiện khâu chuyên môn hành chính lễ tân bảo mật lưu trữ hậu cần đồng bộ chặt chẽ xây dựng tập thể đoàn kết chuyên nghiệp đẩy mạnh ứng dụng khoa học công nghệ chuyển đổi hiện đại hóa phương thức làm việc gặp mặt nguyên chủ tịch lương cường 50 công tác nỗ lực hoàn thành nhiệm vụ giao ủng hộ lãnh đạo cơ quan địa phương cử tri cán bộ văn phòng chủ tịch đề nghị tập thể văn phòng chủ tịch phát huy truyền thống vững kỷ cương nâng chất lượng tham mưu phục vụ hiệu quả hoạt động chủ tịch giai đoạn nguyên chủ tịch lương cường 69 quê phú thọ ủy viên trung ương đảng khóa 11 13 bí thư trung ương đảng hai khóa 12 13 ủy viên chính trị khóa 13 đại biểu quốc hội khóa 15 nhập ngũ 1975 50 công tác quân đội chủ yếu phụ trách công tác chính trị công tác đảng chức vụ ủy quân đoàn 2 ủy quân khu 3 phó chủ nhiệm chủ nhiệm tổng cục chính trị quân đội nhân dân việt nam phong quân hàm đại tướng 2019 5 2024 phân công thường trực ban bí thư 10 2024 quốc hội bầu chức chủ tịch nhiệm kỳ 2021 2026 đại hội đảng 14 đầu 2026 tham gia trung ương khóa',
 'thứ hai đợt nắng nóng diện rộng nhiệt độ 1 2 độ c hôm qua bắc bộ trung bộ 40 độ c miền bắc khu vực tây bắc bộ nắng nóng gay gắt phổ biến 35 37 độ c 39 độ ghi nhận phù yên sơn la 40 2 độ c mường tè lai châu lạc sơn phú thọ xấp xỉ 40 độ đồng bằng bắc bộ nhiệt độ phổ biến 35 36 độ c trạm láng hà nội ghi nhận 36 độ đầu hoài đức 35 độ hà đông 34 độ 33 độ c nho quan ninh bình 39 độ c đồng bằng hiệu ứng đô thị nhiệt độ cảm nhận 2 4 độ c tâm nắng nóng bắc trung bộ nhiệt độ phổ biến 38 39 độ c 39 độ đo 41 độ quỳ châu đô lương trạm tây hiếu xấp xỉ 42 độ c hà tĩnh hương sơn hương khê nóng 40 độ c nắng nóng mở rộng trung trung bộ đà nẵng 39 độ quảng ngãi 38 độ khu vực sơn hòa đăk lăk 39 độ c trung tâm dự báo khí tượng thủy văn quốc gia hoàn lưu nóng tây kết hợp hiệu ứng gió phơn nhiệt cao không khí khô cảm giác oi bức tây nguyên nam bộ ảnh hưởng khối không khí ổn định mây nắng khác biệt hình thế thời tiết cường độ nắng tây bắc bộ trung bộ nóng khô gay gắt nhiệt độ 37 39 độ miền trung 40 độ c nam bộ duy trì 35 37 độ nắng kéo dài gay gắt dự báo nắng nóng diện rộng miền bắc kéo dài 12 4 dần miền trung khả năng duy trì 13 14 4 nam bộ kéo dài 4 liên tục xen kẽ nhiệt trang accuweather mỹ dự báo hà nội nắng nóng cao điểm 9 4 nhiệt 28 38 độ 34 35 độ c khu vực 1 500 m sa pa lào cai dao động 17 29 độ c tuần cơ quan khí tượng cảnh báo nắng nóng gay gắt kết hợp độ ẩm thấp nguy cơ cháy nổ khu dân cư nhu cầu điện tiếp xúc nhiệt',
 '7 4 hội đồng dân tộc ủy ban quốc hội kiện toàn nhân sự phó chủ nhiệm đại biểu hoạt động chuyên trách khóa 16 hội đồng dân tộc phó chủ nhiệm khóa 16 hoàng duy chinh ủy viên trung ương đảng ủy viên ủy ban thường vụ quốc hội quàng văn hương cao thị xuân trần thị hoa ry đinh thị phương lan ủy viên hoạt động chuyên trách hội đồng dân tộc khóa 16 lê nhật thành tráng a dương hoàng văn tuyên leo thị lịch ma thị thúy ủy ban quốc phòng an ninh đối ngoại phó chủ nhiệm khóa 16 vũ hải hà ủy viên trung ương đảng ủy viên ủy ban thường vụ quốc hội nguyễn minh đức nguyễn quốc hùng trần đức thuận nguyễn ngọc hà đinh công sỹ đại biểu chuyên trách ủy ban trần thị hồng an trịnh xuân an trần việt phạm phú bình thái quỳnh mai dung vũ huy khánh võ văn hội phạm ngọc hải phạm đức hoài nguyễn trung kiên ủy ban khoa học công nghệ môi trường 5 phó chủ nhiệm khóa 16 trần văn khải nguyễn phương tuấn tạ đình thi đỗ đức hồng hà nguyễn thị mai phương đại biểu chuyên trách ủy ban ông bà nguyễn văn an nguyễn thị kim nguyễn ngọc sơn vương quốc thắng lê hoàng hải lương văn ngô sỹ cường lê trung thành ủy ban dân nguyện giám sát 4 phó chủ nhiệm khóa 16 ông bà hoàng công trần thị nhị hà lò việt phương mạnh linh đại biểu chuyên trách nguyễn ngọc hùng hoàng nam hải trần hoài nam đỗ khắc hưởng lê thị thúy sen 6 4 quốc hội kiện toàn chức danh lãnh đạo quốc hội chủ nhiệm ủy ban chủ tịch quốc hội trần thanh mẫn tái đắc cử khóa 16 phó chủ tịch quốc hội đỗ văn chiến nguyễn khắc định nguyễn hồng diên nguyễn doãn hai nữ phó chủ tịch quốc hội nguyễn thị thanh nguyễn thị hồng lãnh đạo ủy ban chủ tịch hội đồng dân tộc lâm văn mẫn tổng thư ký quốc hội chủ nhiệm văn phòng quốc hội lê quang chủ nhiệm ủy ban pháp luật tư pháp phan chí hiếu chủ nhiệm ủy ban quốc phòng an ninh đối ngoại lê chủ nhiệm ủy ban kinh tế tài chính phan văn mãi chủ nhiệm ủy ban văn hóa xã hội nguyễn đắc vinh chủ nhiệm ủy ban dân nguyện giám sát lê thị nga chủ nhiệm ủy ban khoa học công nghệ môi trường nguyễn thanh hải chủ nhiệm ủy ban công tác đại biểu nguyễn hữu đông',
 'khói lửa bùng lầu ngã 7 lý thái tổ 10 cũ sức nóng vỡ kính cửa sổ rơi đe dọa đi đường chiều 7 4 15 h30 đám cháy phát lầu 4 tầng rộng 70 m2 nằm đường lê hồng phong phường vườn lài ngã 7 lý thái tổ 200 m tầng thuê mặt bằng quán cà phê cạnh dãy ống văn phòng cửa hàng kinh doanh sầm uất hai nhân viên pha chế phát hiện sự cố chạy thoát thân khói tỏa mù mịt ban công lan cửa sổ lầu hưng hiện trường khói đen bao trùm cửa sổ hàng xóm nhân viên quán cà phê hô uống cà phê chạy sức nóng bể kính cửa sổ rơi xuống đường may mắn trúng hưng đội cảnh sát pccc 2 km nhanh chóng xe chữa cháy chục chiến sĩ hiện trường lính cứu hỏa lăng xịt dập lửa lầu chống cháy lan hỏa hoạn dập tắt 10 phút thương vong tài sản thiêu rụi tường ô cửa sổ ám khói đen nguyên nhân ban đầu chập điện cháy đồ nội thất lầu',
 'hà nội tp hcm tổ chức kiểm định khí thải xe môtô xe máy 1 7 2027 thành phố trung ương 1 7 2028 quyết định thủ tướng chính phủ ban hành quyết định 13 2026 quy định lộ trình áp dụng quy chuẩn kỹ thuật quốc gia khí thải xe môtô xe gắn máy tham gia giao thông đường bộ kiểm định khí thải xe môtô xe gắn máy tham gia giao thông 1 7 2027 hà nội tp hcm 1 7 2028 thành phố trực thuộc trung ương hải phòng huế đà nẵng thơ 1 7 2030 kiểm định áp dụng 28 tỉnh tùy tình hình tỉnh áp dụng quyết định nêu xe môtô dung tích xi lanh 50 cm3 trở sản xuất nhập khẩu 2008 áp dụng 1 giới hạn tối đa cho phép khí thải quy chuẩn kỹ thuật quốc gia khí thải xe môtô xe gắn máy tham gia giao thông đường bộ xe môtô sản xuất nhập khẩu 2008 2016 áp dụng 2 xe môtô sản xuất nhập khẩu 2017 30 6 2026 áp dụng 3 xe môtô sản xuất nhập khẩu 1 7 2026 áp dụng 4 xe gắn máy dung tích xi lanh 50 cm3 sản xuất nhập khẩu 2016 áp dụng 1 xe gắn máy sản xuất nhập khẩu 2017 30 6 2027 áp dụng 2 xe gắn máy sản xuất nhập khẩu 1 7 2027 áp dụng 4 1 1 2028 xe môtô xe gắn máy tham gia giao thông hà nội tp hcm đáp ứng quy định khí thải 2 trở xe môtô xe gắn máy tham gia giao thông phát thải tp hà nội quy định luật thủ đô đáp ứng quy định khí thải nghị quyết hđnd thành phố hiện 74 3 triệu xe máy kiểm định khí thải xe cục đăng kiểm việt nam 5 000 cơ sở tức 5 000 thiết bị đo khí thải 5 000 đăng kiểm viên công tác cơ sở kiểm định đầu tư tận dụng bảo dưỡng xe máy doanh nghiệp hiệp hội nhà sản xuất xe máy việt nam thông tư 92 2025 nông nghiệp môi trường quy chuẩn kỹ thuật quốc gia khí thải xe môtô xe gắn máy tham gia giao thông đường bộ bao gồm 4 cho phép thông số hydrocacbon hc cacbon monoxit co khí thải xe môtô xe gắn máy tham gia giao thông đường bộ giới hạn tối đa cho phép thông số co hc khí thải xe môtô xe gắn máy lắp động cơ cháy cưỡng bức tham gia giao thông đường bộ quy định bảng',
 'thủ tướng lê minh hưng nhấn mạnh điều hành quyết liệt mục tiêu tăng trưởng bền vững giai đoạn 2026 2031 xây dựng bộ máy liêm chính kỷ luật hiệu lực hiệu quả chiều 7 4 quốc hội thông qua nghị quyết bầu lê minh hưng trưởng ban tổ chức trung ương chức thủ tướng trưởng ban tổ chức trung ương hai bầu đứng đầu chính phủ phạm minh phát biểu nhậm chức tân thủ tướng lê minh hưng ý thức sâu sắc vinh dự đi kèm trách nhiệm nặng nề tổ quốc nhân dân phát triển bền vững nhiệm kỳ 2026 2031 lịch sử đòi hỏi đất nước phát triển bứt phá hội nhập nâng tầm vị thế tăng trưởng phát triển bền vững bao trùm nâng đời sống hạnh phúc người dân xác định 5 định hướng trọng tâm xây dựng chính phủ hiện đại kiến tạo phục vụ nhân dân trọng tâm hoàn thiện đồng bộ thể chế rà soát sửa đổi quy định pháp luật cắt giảm tối đa thủ tục hành chính tháo gỡ nghẽn khơi thông nguồn lực xây dựng bộ máy tinh gọn hoạt động hiệu năng hiệu lực hiệu quả thủ tướng thành viên chính phủ đi đôi điều hành tư duy quản trị hiện đại chủ động linh hoạt điều hành kinh tế chính phủ mục tiêu tăng trưởng bền vững thủ tướng nêu mục tiêu tăng trưởng gdp bình quân 10 giai đoạn 2026 2031 mệnh lệnh phát triển chính phủ xác định khoa học công nghệ đổi mới sáng tạo chuyển đổi quốc gia đột phá hàng đầu động lực nâng năng suất năng lực cạnh tranh tự chủ chiến lược thúc đẩy hình thành động lực tăng trưởng phát triển hạ tầng đồng bộ đẩy mạnh chuyển đổi xanh thích ứng biến đổi khí hậu cơ cấu kinh tế xác định kinh tế nhà nước vai trò chủ đạo kinh tế tư nhân động lực chính phủ bảo đảm địa phương doanh nghiệp người dân tham gia đóng góp hưởng lợi công bằng tăng trưởng song song phát triển kinh tế chính phủ cam kết nguồn lực đổi mới căn bản giáo dục đào tạo phát triển nhân lực chất lượng trọng dụng nhân tài hệ thống y tế công cộng nâng năng lực chăm sóc sức khỏe người dân cơ sở chính sách an sinh xã hội hiệu quả bảo đảm chăm lo công nhóm yếu thế văn hóa xác định nền tảng sức mạnh nội sinh dân tộc quốc phòng an ninh củng cố xây dựng thế trận quốc phòng toàn dân gắn thế trận an ninh nhân dân vững chắc đối ngoại chính phủ kiên định đường lối độc lập tự chủ đẩy mạnh ngoại giao kinh tế ngoại giao công nghệ nâng vị thế quốc gia bộ máy chính quyền địa phương hai vận hành 2025 thủ tướng nhiệm vụ trọng tâm bảo đảm vận hành thực chất hiệu lực hiệu quả động lực phát triển chính phủ đẩy mạnh phân cấp phân quyền gắn phân bổ nguồn lực hợp lý nâng năng lực đội ngũ cán bộ xã phường đặc khu thủ tướng nhấn mạnh nguyên tắc địa phương giao địa phương quyết phát huy chủ động linh hoạt dám dám dám trách nhiệm chính quyền cơ sở hài lòng người dân doanh nghiệp thước đo chính phủ xác định tăng cường phối hợp chặt chẽ cơ quan đảng quốc hội mặt trận tổ quốc tổ chức chính trị xã hội cộng đồng doanh nghiệp nhân dân mục tiêu phát triển nhấn mạnh xây dựng chính phủ liêm kỷ luật bản lĩnh trách nhiệm thủ tướng nhân dân nguồn lực bộ máy trong sạch cán bộ liêm chính công vụ kỷ cương né tránh vô cảm nghiêm khuyến khích bảo vệ cán bộ dám nghĩ dám lợi ích hứa tập thể chính phủ bộ ngành địa phương đoàn kết một lòng quyết tâm đất nước giai đoạn phát triển bứt phá giàu mạnh phồn vinh văn minh hạnh phúc thủ tướng lê minh hưng',
 'nguyễn huy tiến công tác ngành kiểm sát kinh qua địa phương trung ương chức viện trưởng viện kiểm sát nhân dân tối cao',
 'nguyễn huy tiến 58 quốc hội bầu chức viện trưởng viện kiểm sát nhân dân tối cao nhiệm kỳ 2026 2031 474 474 đại biểu có mặt tán thành chiều 7 4 nguyễn huy tiến tiến sĩ luật ủy viên trung ương đảng khóa 14 đại biểu quốc hội khóa 16 đầu sự nghiệp công tác ngành tư pháp quảng ninh thái bình làm việc viện thực hành quyền công tố kiểm sát xét xử phúc thẩm hà nội viện kiểm sát nhân dân tối cao lần lượt phó viện trưởng viện trưởng kinh qua cương vị viện trưởng viện kiểm sát nhân dân tỉnh quảng bình viện trưởng viện kiểm sát nhân dân hà nội vụ trưởng vụ thực hành quyền công tố kiểm sát điều tra án tham nhũng chức vụ vụ 5 viện kiểm sát nhân dân tối cao 9 2018 bổ nhiệm phó viện trưởng viện kiểm sát nhân dân tối cao quốc hội bầu chức viện trưởng viện kiểm sát nhân dân tối cao 8 2024 đảm nhiệm cương vị hiện viện kiểm sát nhân dân tối cao 6 phó viện trưởng hồ đức nguyễn duy giảng nguyễn quang dũng tạ quang khải trần hải quân nguyễn đức thái viện kiểm sát nhân dân cơ quan thực hành quyền công tố kiểm sát hoạt động tư pháp nhiệm vụ bảo vệ hiến pháp pháp luật quyền con người quyền công dân lợi ích nhà nước tổ chức bảo đảm pháp luật chấp hành nghiêm chỉnh thống nhất quy định viện trưởng viện kiểm sát nhân dân tối cao quốc hội bầu miễn nhiệm bãi nhiệm đề nghị chủ tịch nhiệm kỳ nhiệm kỳ quốc hội quốc hội nhiệm kỳ viện trưởng nhiệm vụ quốc hội khóa bầu nhân sự thay thế phó viện trưởng viện kiểm sát nhân dân tối cao chủ tịch bổ nhiệm miễn nhiệm cách chức đề nghị viện trưởng',
 'võ thị ánh xuân phó chủ tịch nhiệm kỳ 2021 2026 quốc hội bầu chức phó chủ tịch nhiệm kỳ 2026 2031 nghị quyết bầu võ thị ánh xuân chức phó chủ tịch quốc hội thông qua chiều 7 4 485 485 đại biểu có mặt biểu quyết đồng ý võ thị ánh xuân 56 quê an giang thạc sĩ quản lý công cử nhân sư phạm hóa học bí thư trung ương đảng khóa 14 ủy viên dự khuyết khóa 11 ủy viên trung ương 3 khóa liên tiếp 12 14 đại biểu quốc hội khóa liên tiếp 14 16 khởi đầu sự nghiệp giáo viên phổ thông chuyên viên văn phòng tỉnh ủy an giang trải địa phương phó chủ tịch chủ tịch hội liên hiệp phụ nữ tỉnh phó ban dân vận tỉnh ủy bí thư thị ủy tân châu đầu 2013 phó chủ tịch ubnd tỉnh an giang hai đảm nhiệm cương vị bí thư tỉnh ủy an giang công tác địa phương 4 2021 võ thị ánh xuân quốc hội bầu chức phó chủ tịch đảm nhiệm vai trò hai đảm nhiệm quyền chủ tịch đầu 2023 đầu 2024 đại hội đảng 14 hồi 1 2026 tái cử trung ương bầu ban bí thư hiến pháp quy định phó chủ tịch quốc hội bầu đại biểu quốc hội phó chủ tịch giúp chủ tịch nhiệm vụ chủ tịch ủy nhiệm nhiệm vụ chủ tịch làm việc phó chủ tịch quyền chủ tịch trường hợp khuyết chủ tịch phó chủ tịch quyền chủ tịch quốc hội bầu chủ tịch',
 'tổng liên đoàn lao động việt nam tổ chức ý kiến lao động phương án hoán đổi nghỉ lễ 4 cơ sở đề nghị 7 4 ngọ duy phó chủ tịch tổng liên đoàn lao động việt nam khảo sát chiều kiến nghị công đoàn cơ sở lao động nghiên cứu hoán đổi kỳ nghỉ lễ kéo dài khảo sát nghỉ lễ tuần song cơ quan lắng nghe ý kiến lao động cơ sở quy định pháp luật hài hòa lợi ích đề xuất chính thức nội vụ phương án hoán đổi công bố dựa tổng hợp ý kiến phó chủ tịch công đoàn giỗ tổ 10 3 âm lịch rơi chủ nhật tức 26 4 quy định nghỉ bù làm việc kế tiếp tức hai 27 4 song doanh nghiệp kiến nghị lịch nghỉ bù tư 29 4 thứ bảy 2 5 kỳ nghỉ lễ kéo dài nghỉ luật lao động làm việc doanh nghiệp chế độ nghỉ hàng tuần đi thứ bảy kỳ nghỉ lễ ngắt quãng xen kẽ làm việc bình thường quy định nghỉ bù kế tiếp lễ trùng tuần đôi lúc tình huống ý kiến cần thiết lãnh đạo cục việc làm nội vụ hôm 3 4 chủ trương hoán đổi hai kỳ nghỉ lễ 4 bộ luật lao động thông báo nghỉ lễ tết 2026 giỗ tổ hùng vương 10 3 âm lịch nghỉ dịp 30 4 1 5 nghỉ hai lịch nghỉ áp dụng công chức viên chức lao động khu vực nhà nước giỗ tổ tuần doanh nghiệp khu vực tư nhân chủ động thông báo hoán đổi làm việc bình thường phép nối liền hai kỳ lễ lao động nghỉ 8 9 song doanh nghiệp quy định bộ luật lao động nghỉ giỗ tổ hùng vương hai dịp 30 4 1 5 giỗ tổ hùng vương 10 3 âm lịch rơi chủ nhật 26 4 lao động nghỉ bù hai 27 4 chế độ hai nghỉ hàng tuần đợt nghỉ lễ kéo dài liên tục thứ bảy 25 4 hai 27 4 chế độ nghỉ chủ nhật hàng tuần nghỉ lễ hai 26 27 4 tương tự kỳ nghỉ lễ 30 4 1 5 lao động chế độ hai nghỉ hàng tuần đợt nghỉ lễ bốn liên tục chủ nhật tức 30 4 3 5 chế độ nghỉ hàng tuần nghỉ hai 30 4 1 5 trường hợp làm việc nghỉ hàng tuần kỳ lễ lao động 200 lương làm việc nghỉ hàng tuần trùng nghỉ lễ 300 tiền lương',
 'cương vị chánh án tòa án nhân dân tối cao nguyễn văn quảng cương vị ngành tư pháp hải phòng 5 bí thư đà nẵng',

In [32]:
df['clean_texts'] = result
df

,title,url,texts,author,category,published_at,source,content_block,clean_texts
0,Lao động trung niên tìm việc nhiều nhưng thị t...,https://vnexpress.net/lao-dong-trung-nien-tim-...,Gần 40% số người tìm việc thuộc nhóm trung niê...,Lê Tuyết,Thời sự,"Thứ tư, 8/4/2026, 00:00 (GMT+7)",VnExpress,"[{'type': 'text', 'content': 'Gần 40% số người...",40 trung niên 36 49 song doanh nghiệp nhu cầu ...
1,Tổng Bí thư Tô Lâm gặp mặt cán bộ Văn phòng Ch...,https://vnexpress.net/tong-bi-thu-to-lam-gap-m...,Sau khi được Quốc hội bầu giữ chức Chủ tịch nư...,Vũ Tuân,Thời sự,"Thứ ba, 7/4/2026, 22:40 (GMT+7)",VnExpress,"[{'type': 'text', 'content': 'Sau khi được Quố...",quốc hội bầu chức chủ tịch nhiệm kỳ 2026 2031 ...
2,Nhiệt độ nhiều nơi vượt 40 độ C,https://vnexpress.net/nhiet-do-nhieu-noi-vuot-...,Cả nước bước vào ngày thứ hai của đợt nắng nón...,Gia Chính,Thời sự,"Thứ ba, 7/4/2026, 20:49 (GMT+7)",VnExpress,"[{'type': 'text', 'content': 'Cả nước bước vào...",thứ hai đợt nắng nóng diện rộng nhiệt độ 1 2 đ...
3,Các ủy ban của Quốc hội kiện toàn nhân sự,https://vnexpress.net/cac-uy-ban-cua-quoc-hoi-...,"Ngày 7/4, Hội đồng Dân tộc và một số Ủy ban củ...",Sơn Hà,Thời sự,"Thứ ba, 7/4/2026, 20:30 (GMT+7)",VnExpress,"[{'type': 'text', 'content': 'Ngày 7/4, Hội đồ...",7 4 hội đồng dân tộc ủy ban quốc hội kiện toàn...
4,Cháy nhà 4 tầng ở trung tâm TP HCM,https://vnexpress.net/chay-nha-4-tang-o-trung-...,Khói lửa bùng lên từ lầu một ngôi nhà gần ngã ...,Đình Văn,Thời sự,"Thứ ba, 7/4/2026, 17:45 (GMT+7)",VnExpress,"[{'type': 'text', 'content': 'Khói lửa bùng lê...",khói lửa bùng lầu ngã 7 lý thái tổ 10 cũ sức n...
...,...,...,...,...,...,...,...,...,...
2295,"Cận Vía Thần Tài, một Tiệm vàng lớn tuyên bố c...",https://cafebiz.vn/can-ngay-via-than-tai-mot-t...,Tiệm vàng với 34 cơ sở trên toàn quốc khẳng đị...,Phan Trang,BizMoney,24/02/2026 10:59 AM,CafeBiz,"[{'type': 'text', 'content': 'Tiệm vàng với 34...",tiệm vàng 34 cơ sở toàn quốc sẵn vàng 24 k 0 1...
2296,Giá vàng sáng 24/2 vượt 5.200 USD/ounce,https://cafebiz.vn/gia-vang-sang-24-2-vuot-520...,"Chỉ trong một ngày, giá vàng đã có mức tăng mạ...",Huyền Băng,BizMoney,24/02/2026 07:10 AM,CafeBiz,"[{'type': 'text', 'content': 'Chỉ trong một ng...",giá vàng 24 thị trường tài chính toàn cầu chứn...
2297,Giá vàng thế giới chạm mốc 5.200 USD/ounce,https://cafebiz.vn/gia-vang-the-gioi-cham-moc-...,Thị trường vàng ngày càng nóng lên.. Trong 24 ...,Băng Băng,BizMoney,23/02/2026 22:25 PM,CafeBiz,"[{'type': 'text', 'content': 'Thị trường vàng ...",thị trường vàng nóng 24 thị trường kim loại qu...
2298,"Trước ngày vía Thần Tài: Không chỉ vàng, giá b...",https://cafebiz.vn/truoc-ngay-via-than-tai-kho...,"Tại thị trường trong nước, giá bạc cũng đã tăn...",Ngọc Tú,BizMoney,23/02/2026 10:20 AM,CafeBiz,"[{'type': 'text', 'content': 'Tại thị trường t...",thị trường giá bạc 15 triệu đồng kg tết nguyên...
2299,Giá vàng thế giới lội ngược dòng trong Tết Ngu...,https://cafebiz.vn/gia-vang-the-gioi-loi-nguoc...,Thị trường vàng đã có cú lội ngược dòng trong ...,Huyền Băng,BizMoney,23/02/2026 08:57 AM,CafeBiz,"[{'type': 'text', 'content': 'Thị trường vàng ...",thị trường vàng cú lội ngược dòng tuần thị trư...